
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [1]:
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [2]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9]) 

reshaped_arr = arr.reshape(3, 3)

print(reshaped_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Access the element at the second row, second column.


In [18]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9]) 

reshaped_arr = arr.reshape(3, 3)

print(reshaped_arr)

element = reshaped_arr[1, 1]

print(element)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
5


Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [22]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

sum_arr = arr1 + arr2

print("Element-wise addition:", sum_arr)  

difference_arr = arr2 - arr1

print("Element-wise subtraction:", difference_arr)  

product_arr = arr1 * arr2

print("Element-wise multiplication:", product_arr)  

division_arr = arr2 / arr1

print("Element-wise division:", division_arr) 

Element-wise addition: [5 7 9]
Element-wise subtraction: [3 3 3]
Element-wise multiplication: [ 4 10 18]
Element-wise division: [4.  2.5 2. ]


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

sum_of_elements = np.sum(arr)

mean_of_elements = np.mean(arr)

std_dev = np.std(arr)

print("Sum:", sum_of_elements)
print("Mean:", mean_of_elements)
print("Standard deviation:", std_dev)

Sum: 15
Mean: 3.0
Standard deviation: 1.4142135623730951


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped_arr = arr.reshape(2, 3)

print(reshaped_arr)

[[1 2 3]
 [4 5 6]]



# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [7]:
import numpy as np

min_value = 0

max_value = 100

random_arr = np.random.randint(min_value, max_value, size=(5, 5))

print(random_arr)

[[98 37 59 25 93]
 [44 13 43 21 41]
 [28 53  1 77 29]
 [35 89 91 50 63]
 [22 62 52 30 44]]


Replace all values in the sub-array with a specific value.


In [8]:
import numpy as np

random_arr = np.random.randint(0, 100, size=(5, 5))

print("Original array:\n", random_arr)

start_row = 1
end_row = 3
start_col = 2
end_col = 4

replacement_value = 99

random_arr[start_row:end_row, start_col:end_col] = replacement_value

print("\nArray after replacing sub-array:\n", random_arr)

Original array:
 [[97 81 10 98 72]
 [94 30 83 62  2]
 [86  1 55 97 12]
 [72 34 81 72 87]
 [73 30  8 81 67]]

Array after replacing sub-array:
 [[97 81 10 98 72]
 [94 30 99 99  2]
 [86  1 99 99 12]
 [72 34 81 72 87]
 [73 30  8 81 67]]


Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [9]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

sub_array = arr[1:3, 1:3]

print(sub_array)

[[4]
 [6]]



# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [10]:
import numpy as np

shape = (3, 3)

arr = np.arange(shape[0] * shape[1]).reshape(shape)

print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [11]:
import numpy as np

shape = (3, 3)

arr = np.arange(shape[0] * shape[1]).reshape(shape)

one_d_array = np.array([10, 20, 30])

arr += one_d_array[:, None]  # Reshape one_d_array to a column vector

print(arr)

[[10 11 12]
 [23 24 25]
 [36 37 38]]


# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [12]:
import numpy as np

arr1 = np.random.randint(1, 100, size=(3, 3))

arr2 = np.random.randint(1, 100, size=(3, 3))

print("Array 1:\n", arr1)

print("Array 2:\n", arr2)


Array 1:
 [[28 66 66]
 [32 57 29]
 [26 43 51]]
Array 2:
 [[93 76 52]
 [54 23 71]
 [74 88 60]]


In [13]:
import numpy as np

arr1 = np.random.randint(1, 100, size=(3, 3))

arr2 = np.random.randint(1, 100, size=(3, 3))

concatenated_horizontal = np.concatenate((arr1, arr2), axis=1)

concatenated_vertical = np.concatenate((arr1, arr2), axis=0)

print("\nConcatenated horizontally:\n", concatenated_horizontal)

print("\nConcatenated vertically:\n", concatenated_vertical)



Concatenated horizontally:
 [[35 46 78 13 67 15]
 [41 30 68 61 65 24]
 [94 18 99 14 34 63]]

Concatenated vertically:
 [[35 46 78]
 [41 30 68]
 [94 18 99]
 [13 67 15]
 [61 65 24]
 [14 34 63]]


In [14]:
import numpy as np

arr1 = np.random.randint(1, 100, size=(3, 3))

arr2 = np.random.randint(1, 100, size=(3, 3))

arr1_split = concatenated_horizontal[:, :3]

arr2_split = concatenated_horizontal[:, 3:]

arr1_split_v = concatenated_vertical[:3, :]

arr2_split_v = concatenated_vertical[3:, :]

print("\nSplit from concatenated horizontal (arr1):\n", arr1_split)
print("\nSplit from concatenated horizontal (arr2):\n", arr2_split)

print("\nSplit from concatenated vertical (arr1):\n", arr1_split_v)

print("\nSplit from concatenated vertical (arr2):\n", arr2_split_v)


Split from concatenated horizontal (arr1):
 [[35 46 78]
 [41 30 68]
 [94 18 99]]

Split from concatenated horizontal (arr2):
 [[13 67 15]
 [61 65 24]
 [14 34 63]]

Split from concatenated vertical (arr1):
 [[35 46 78]
 [41 30 68]
 [94 18 99]]

Split from concatenated vertical (arr2):
 [[13 67 15]
 [61 65 24]
 [14 34 63]]


# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [15]:
import numpy as np

arr = np.array([1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5])

mode_counts = {}

for num in arr:
    
  if num in mode_counts:
      
    mode_counts[num] += 1
  else:
    mode_counts[num] = 1

max_count = max(mode_counts.values())

modes = [num for num, count in mode_counts.items() if count == max_count]

if len(modes) == 1:
    
  print("Mode:", modes[0])
else:
  print("Modes:", modes)

Mode: 1


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

